#jinja2:  variable_start_string: "[%" , variable_end_string: "%]"
---

# usage: ansible-playbook -i hosts edu-kiosk-description.yml 

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install Leafpad
      apt: name=leafpad state=latest install_recommends=no
    - name: Install basic software
      apt: name={{ item }} state=latest
      with_items:
        - chromium-browser 
        - blender
        - preload
        - vim
        - gimp
        - libreoffice
        - vlc
        - cron-apt
