#jinja2:  variable_start_string: "[%" , variable_end_string: "%]"
---

# usage: ansible-playbook -i hosts edu-kiosk-description.yml 

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Upgrade all packages
      apt: upgrade=dist
    - name: Install basic software
      apt: name={{ item }} state=latest
      with_items:
        - chromium-browser 
        - blender
        - preload
        - vim
        - gimp
        - libreoffice
        - vlc
#    - name: Schedule description to be put in action at 9 AM every day
#      cron: name="Schedule main script" hour="9" job="sh /home/edu-admin/Github/elementary-os-kiosk-description/main.sh"

# TODO
# set finnish keyboard
# set language to finnish
# maintenance scripts and updates bound to boot
# settings to guest's skel
# setup icons
# Google Docs integration
