#jinja2:  variable_start_string: "[%" , variable_end_string: "%]"
---

# usage: ansible-playbook -i hosts edu-kiosk-description.yml 

- hosts: 127.0.0.1
  connection: local
  tasks:

#    - name: Set main.sh to be run at every boot
#      cron: name="Main script to be run at every boot" special_time="reboot" job="bash /home/edu-admin/Github/elementary-os-kiosk-description/main.sh"

    - name: Update the list of available packages (= apt-get update)
      apt: update_cache=yes
    - name: Upgrade all packages
      apt: upgrade=dist

    - name: Install basic software
      apt: name={{ item }} state=present
      with_items:
        - chromium-browser 
        - gnome-shell
        - blender
        - preload
        - vim
        - gimp
        - libreoffice
        - vlc
        - imagemagick
        - openshot
        - shutter
        - tmux
        - irssi
        - audacity

#    - name: Folder for mime settings to make Chromium default
#      file: path=/etc/guest-session/skel/.local/share/applications state=directory
#    - name: Make Chromium the default browser
#      copy: src=templates/etc_guest-session_skel_.local_share_applications_mimeapps.list dest=/etc/guest-session/skel/.local/share/applications/mimeapps.list
#    - name: Enable no-first-run and incognito for Chromium
#      copy: src=templates/usr_share_applications_chromium-browser.desktop dest=/usr/share/applications/chromium-browser.desktop

    - name: Copy file including Firefox preference overrides
      copy: src=templates/usr_lib_firefox_defaults_pref_vendor-gre.js dest=/usr/lib/firefox/defaults/pref/vendor-gre.js

    - name: Disable crash notifications (Apport)
      copy: src=templates/etc_default_apport dest=/etc/default/apport

    - name: Create directory for guest session
      file: path='/etc/guest-session' state=directory

    - name: Create directory for guest session preferences
      file: path='/etc/guest-session/skel/.config/dconf' state=directory
    - name: Copy preferences for guest session such as set of launchers
      copy: src=templates/etc_guest-session_skel_.config_dconf_user dest=/etc/guest-session/skel/.config/dconf/user

    - name: Copy LightDM settings file in its place
      copy: src=templates/etc_lightdm_lightdm.conf dest=/etc/lightdm/lightdm.conf

#    - name: Copy desired launchers for guest session from the repo
#      template: src=templates/etc_guest-session_skel_.config_plank_dock1_launchers_{{ item }}.dockitem dest=/etc/guest-session/skel/.config/plank/dock1/launchers/{{ item }}.dockitem 
#      with_items:
#        - chromium-browser
#        - gimp
#        - google-drive
#        - pantheon-files

#    - name: Set prefs.sh for guest session
#      copy: src='templates/etc_guest-session_prefs.sh' dest='/etc/guest-session/prefs.sh'

    - name: Copy needed files to create a custom launcher for Google Drive
      copy: src=templates/usr_share_applications_google-drive.desktop dest=/usr/share/applications/google-drive.desktop 
    - name: Copy the icon for Google Drive launcher
      copy: src=templates/usr_share_pixmaps_google-drive.png dest=/usr/share/pixmaps/google-drive.png

    - name: Copy needed files to create a custom launcher for Volume_1
      copy: src=templates/usr_share_applications_volume-1.desktop dest=/usr/share/applications/volume-1.desktop 

#    - name: Set main.sh to be run on every boot
#      action: template src=templates/etc_rc.local dest=/etc/rc.local


#    - name: Schedule description to be put in action at 9 AM every day
#      cron: name="Schedule main script" hour="9" job="sh /home/edu-admin/Github/elementary-os-kiosk-description/main.sh"

# TODO
# set finnish keyboard
# set language to finnish
# maintenance scripts and updates bound to boot
# settings to guest's skel
# setup icons
# Google Docs integration
